# Generated by Django 5.1.1 on 2024-09-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('posts', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(default='edify', related_name='posts', to='hashtag.hashtag'),
        ),
    ]
