# Generated by Django 5.1.1 on 2024-09-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('members', '0003_alter_member_general_rating_alter_member_num_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_desc', models.CharField(max_length=800)),
                ('video_video', models.FileField(upload_to='video/%y/%m/%d')),
                ('video_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
