# Generated by Django 5.0.7 on 2024-09-21 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postlike', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='postlike_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 23, 47, 29, 89803)),
        ),
    ]
