# Generated by Django 5.1.1 on 2024-09-22 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postlike', '0005_alter_postlike_postlike_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='postlike_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 14, 32, 4, 746678)),
        ),
    ]
