# Generated by Django 5.1.1 on 2024-09-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_course_name_alter_courses_course_title'),
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='hashtags',
            field=models.ManyToManyField(default='edify', related_name='courses', to='hashtag.hashtag'),
        ),
    ]
