# Generated by Django 4.2.15 on 2024-12-20 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcomment', '0008_alter_postcomment_postcomment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='postcomment_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 11, 57, 25, 968280)),
        ),
    ]
