# Generated by Django 5.1.1 on 2024-09-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtag', '0001_initial'),
        ('members', '0003_alter_member_general_rating_alter_member_num_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=100)),
                ('short_video', models.FileField(upload_to='upload/%y/%m/%d')),
                ('short_likes', models.IntegerField(default=0)),
                ('short_comments', models.IntegerField(default=0)),
                ('short_time', models.DateTimeField(auto_now_add=True)),
                ('hashtags', models.ManyToManyField(related_name='shortvideos', to='hashtag.hashtag')),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
