# Generated by Django 5.1.1 on 2024-09-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('shortvideo', '0002_shortvideo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortvideo',
            name='hashtags',
            field=models.ManyToManyField(default='edify', related_name='shortvideos', to='hashtag.hashtag'),
        ),
    ]
