# Generated by Django 4.2.15 on 2024-09-17 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('general_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('num_courses', models.IntegerField(default=0)),
                ('num_reviews', models.IntegerField(default=0)),
                ('num_followers', models.IntegerField(default=0)),
                ('is_instructor', models.BooleanField(default=False)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('my_posts', models.JSONField(default=list)),
                ('my_shorts', models.JSONField(default=list)),
                ('my_courses', models.JSONField(default=list)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('saved_courses', models.JSONField(default=list)),
                ('saved_shorts', models.JSONField(default=list)),
                ('saved_posts', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
