# Generated by Django 4.2.15 on 2024-09-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_my_courses_alter_member_my_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='general_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='member',
            name='num_courses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='num_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
